In [1]:
import numpy as np

In [2]:
R = np.array([[np.nan, 4, 3, 1, 2, np.nan],
              [5, 5, 4, np.nan, 3, 3],
              [4, np.nan, 5, 3, 2, np.nan],
              [np.nan, 3, np.nan, 2, 1, 1],
              [2, 1, 2, 4, np.nan, 3]])
R

array([[nan,  4.,  3.,  1.,  2., nan],
       [ 5.,  5.,  4., nan,  3.,  3.],
       [ 4., nan,  5.,  3.,  2., nan],
       [nan,  3., nan,  2.,  1.,  1.],
       [ 2.,  1.,  2.,  4., nan,  3.]])

In [3]:
U = np.arange(R.shape[0])
U

array([0, 1, 2, 3, 4])

In [4]:
I = np.arange(R.shape[1])
I

array([0, 1, 2, 3, 4, 5])

In [5]:
U.size

5

In [6]:
I.size

6

In [7]:
R[0,1]

np.float64(4.0)

In [13]:
R.size

30

In [14]:
~np.isnan(R)

array([[False,  True,  True,  True,  True, False],
       [ True,  True,  True, False,  True,  True],
       [ True, False,  True,  True,  True, False],
       [False,  True, False,  True,  True,  True],
       [ True,  True,  True,  True, False,  True]])

In [15]:
np.sum(~np.isnan(R))

np.int64(22)

In [17]:
sparsity = np.sum(np.isnan(R)) / R.size
sparsity

np.float64(0.26666666666666666)

In [22]:
I[~np.isnan(R[0])]

array([1, 2, 3, 4])

In [23]:
Iu = [I[~np.isnan(R[u])] for u in U]
Iu

[array([1, 2, 3, 4]),
 array([0, 1, 2, 4, 5]),
 array([0, 2, 3, 4]),
 array([1, 3, 4, 5]),
 array([0, 1, 2, 3, 5])]

In [24]:
np.intersect1d(Iu[0], Iu[1])

array([1, 2, 4])

In [30]:
U[~np.isnan(R[:, 0])]

array([1, 2, 4])

In [32]:
Ui = [U[~np.isnan(R[:, i])] for i in I]
Ui

[array([1, 2, 4]),
 array([0, 1, 3, 4]),
 array([0, 1, 2, 4]),
 array([0, 2, 3, 4]),
 array([0, 1, 2, 3]),
 array([1, 3, 4])]

In [33]:
np.intersect1d(Ui[0], Ui[4])

array([1, 2])

In [50]:
np.nanmean(R)

np.float64(2.8636363636363638)