In [1]:
import numpy as np

In [2]:
Du = np.array([[5,3,1],
               [6,2,1],
               [4,1,1],
               [8,5,-1],
               [2,4,-1],
               [3,6,-1],
               [7,6,-1],
               [4,2,np.nan],
               [5,1,np.nan],
               [8,6,np.nan],
               [3,4,np.nan],
               [4,7,np.nan],
               [4,4,np.nan]])
Du

array([[ 5.,  3.,  1.],
       [ 6.,  2.,  1.],
       [ 4.,  1.,  1.],
       [ 8.,  5., -1.],
       [ 2.,  4., -1.],
       [ 3.,  6., -1.],
       [ 7.,  6., -1.],
       [ 4.,  2., nan],
       [ 5.,  1., nan],
       [ 8.,  6., nan],
       [ 3.,  4., nan],
       [ 4.,  7., nan],
       [ 4.,  4., nan]])

In [3]:
Du.shape

(13, 3)

In [4]:
Du.shape[0]

13

In [5]:
Du.shape[1]

3

In [7]:
Du.size

39

In [9]:
id_item = np.arange(Du.shape[0])
id_item

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [10]:
Du[:, [0, 1]]

array([[5., 3.],
       [6., 2.],
       [4., 1.],
       [8., 5.],
       [2., 4.],
       [3., 6.],
       [7., 6.],
       [4., 2.],
       [5., 1.],
       [8., 6.],
       [3., 4.],
       [4., 7.],
       [4., 4.]])

In [11]:
Du[0, [0, 1]]

array([5., 3.])

In [13]:
ru = Du[:,2]
ru

array([ 1.,  1.,  1., -1., -1., -1., -1., nan, nan, nan, nan, nan, nan])

In [14]:
ru.shape

(13,)

In [15]:
ru.size

13

In [16]:
ru[2:5]

array([ 1., -1., -1.])

In [17]:
ru[::-1]

array([nan, nan, nan, nan, nan, nan, -1., -1., -1., -1.,  1.,  1.,  1.])

In [18]:
ru[0]

np.float64(1.0)

In [19]:
np.isnan(ru)

array([False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True])

In [20]:
~np.isnan(ru)

array([ True,  True,  True,  True,  True,  True,  True, False, False,
       False, False, False, False])

In [22]:
id_item[~np.isnan(ru)]

array([0, 1, 2, 3, 4, 5, 6])

In [23]:
np.where(ru == 1)

(array([0, 1, 2]),)

In [24]:
np.where(ru == -1)

(array([3, 4, 5, 6]),)

In [25]:
id_item[np.isnan(ru)]

array([ 7,  8,  9, 10, 11, 12])

In [26]:
DuL = Du[~np.isnan(ru)]
DuL

array([[ 5.,  3.,  1.],
       [ 6.,  2.,  1.],
       [ 4.,  1.,  1.],
       [ 8.,  5., -1.],
       [ 2.,  4., -1.],
       [ 3.,  6., -1.],
       [ 7.,  6., -1.]])

In [27]:
DuL.shape[0]

7

In [32]:
DuL[(DuL[:,2] == 1)].shape[0]

3

In [33]:
DuL[(DuL[:,2] == -1)].shape[0]

4

In [34]:
DuU = Du[np.isnan(Du[:,2])]
DuU

array([[ 4.,  2., nan],
       [ 5.,  1., nan],
       [ 8.,  6., nan],
       [ 3.,  4., nan],
       [ 4.,  7., nan],
       [ 4.,  4., nan]])

In [35]:
DuU.shape[0]

6